-- VQTZ2025011203__create_recorrencia_tables.sql (ia-core-quartz-service)
-- Creates the recurrence tables for RFC 5545 support
-- Author: IA
-- Dependencies: VQTZ2025011202__create_periodicidade_table.sql

-- Tabelas para RECORRENCIA (RRULE)
CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_DIA_SEMANA (
    periodicidade_id BIGINT NOT NULL,
    by_day VARCHAR(10),
    CONSTRAINT fk_rec_dia_semana FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_DIA_MES (
    periodicidade_id BIGINT NOT NULL,
    by_month_day INTEGER,
    CONSTRAINT fk_rec_dia_mes FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_MES (
    periodicidade_id BIGINT NOT NULL,
    by_month VARCHAR(10),
    CONSTRAINT fk_rec_mes FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_POSICAO (
    periodicidade_id BIGINT NOT NULL,
    by_set_position INTEGER,
    CONSTRAINT fk_rec_posicao FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_DIA_ANO (
    periodicidade_id BIGINT NOT NULL,
    by_year_day INTEGER,
    CONSTRAINT fk_rec_dia_ano FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_SEMANA_ANO (
    periodicidade_id BIGINT NOT NULL,
    by_week_no INTEGER,
    CONSTRAINT fk_rec_semana_ano FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_HORA (
    periodicidade_id BIGINT NOT NULL,
    by_hour INTEGER,
    CONSTRAINT fk_rec_hora FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_MINUTO (
    periodicidade_id BIGINT NOT NULL,
    by_minute INTEGER,
    CONSTRAINT fk_rec_minuto FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_RECORRENCIA_SEGUNDO (
    periodicidade_id BIGINT NOT NULL,
    by_second INTEGER,
    CONSTRAINT fk_rec_segundo FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rec_dia_semana ON QUARTZ.QRTZ_RECORRENCIA_DIA_SEMANA(periodicidade_id);
CREATE INDEX IF NOT EXISTS idx_rec_dia_mes ON QUARTZ.QRTZ_RECORRENCIA_DIA_MES(periodicidade_id);
CREATE INDEX IF NOT EXISTS idx_rec_mes ON QUARTZ.QRTZ_RECORRENCIA_MES(periodicidade_id);

-- Tabelas para EXCLUSAO_RECURRENCE (EXRULE)
CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_DIA_SEMANA (
    periodicidade_id BIGINT NOT NULL,
    ex_by_day VARCHAR(10),
    CONSTRAINT fk_exc_dia_semana FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_DIA_MES (
    periodicidade_id BIGINT NOT NULL,
    ex_by_month_day INTEGER,
    CONSTRAINT fk_exc_dia_mes FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_MES (
    periodicidade_id BIGINT NOT NULL,
    ex_by_month VARCHAR(10),
    CONSTRAINT fk_exc_mes FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_POSICAO (
    periodicidade_id BIGINT NOT NULL,
    ex_by_set_position INTEGER,
    CONSTRAINT fk_exc_posicao FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_DIA_ANO (
    periodicidade_id BIGINT NOT NULL,
    ex_by_year_day INTEGER,
    CONSTRAINT fk_exc_dia_ano FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_SEMANA_ANO (
    periodicidade_id BIGINT NOT NULL,
    ex_by_week_no INTEGER,
    CONSTRAINT fk_exc_semana_ano FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_HORA (
    periodicidade_id BIGINT NOT NULL,
    ex_by_hour INTEGER,
    CONSTRAINT fk_exc_hora FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_MINUTO (
    periodicidade_id BIGINT NOT NULL,
    ex_by_minute INTEGER,
    CONSTRAINT fk_exc_minuto FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTZ.QRTZ_EXC_RECORRENCIA_SEGUNDO (
    periodicidade_id BIGINT NOT NULL,
    ex_by_second INTEGER,
    CONSTRAINT fk_exc_segundo FOREIGN KEY (periodicidade_id) REFERENCES QUARTZ.QRTZ_PERIODICIDADE(id) ON DELETE CASCADE
);